name: Sync fork with upstream

on:
  schedule:
    # Every weekday at 03:00 UTC
    - cron: "0 3 * * 1-5"
  workflow_dispatch:

permissions:
  contents: write  # required to push to the repository

jobs:
  sync:
    name: Sync `main` with upstream
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0            # fetch full history so we can merge

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/nhsuk/manage-vaccinations-in-schools.git || true

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream branch
        run: |
          git checkout main
          # Try fast-forward first; if that fails, do a regular merge with a standard message
          git merge --ff-only upstream/main || \
          git merge --no-edit upstream/main

      - name: Push back to fork (if there were changes)
        run: |
          # Only push if there are new commits on main that are not on origin/main
          if ! git diff --quiet origin/main..HEAD; then
            git push origin main
          else
            echo "No changes to push"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}